### ISSUE TITLE
Incompatible with node-jasmine 2.0.0

### ISSUE THREAD

**Issue by thodic** [alex-pollan/gulp-jasmine-node#4]
Using node-jasmine 2.0.0 currently throws `TypeError: jasmine.getEnv is not a function` on line 6 of `gulp-jasmine-node\index.js`.

I understand node-jasmine 2.0.0 is currently in beta but I have found it stable enough to use. I would love to use it with `gulp-jasmine-node` rather than resorting to `gulp-shell` or similar command line interfaces.

Maybe this could be added to a new branch?

**Comment by alex-pollan** [comment]
@tedswag I'll look into it

**Comment by alex-pollan** [comment]
Ok, there is no straightforward refactor possible because in the Jasmine2.0 branch they hid their _jasmine wrapper_ interface. The new interface doesn't fit with this gulp task wrapper.
IMO a solution could be to reuse their _jasmine loader_ code directly here and to remove the dependency on their _jasmine-node_ module. It would provide this module autonomy but also some headaches (bridging with jasmine) that I wanted to avoid when I decided to sit on top of their module.
I'll continue investigating... and hey...thanks for the tip!

**Comment by alex-pollan** [comment]
This module seems to be what you need: https://github.com/sindresorhus/gulp-jasmine
They provide support to jasmine 2. 
Any change that I could make would result in something similar so I won't update this module. 
I will close this issue now. Thanks anyway!
